# Generated by Django 3.2.13 on 2022-07-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('called_back', models.CharField(max_length=50, verbose_name='Presumptive cases called back')),
                ('responded', models.CharField(max_length=50, verbose_name='Presumptive cases responded (reached?)')),
                ('disclosed_not_tested', models.CharField(max_length=50, verbose_name='Presumptive cases reached who disclosed not tested')),
                ('disclosed_tested', models.CharField(max_length=50, verbose_name='Presumptive cases reached who disclosed tested')),
                ('disclosed_result', models.CharField(max_length=50, verbose_name='Presumptive cases reached who did not disclose result')),
                ('disclosed_positive', models.CharField(max_length=50, verbose_name='Presumptive cases reached who disclosed Positive')),
                ('disclosed_negative', models.CharField(max_length=50, verbose_name='Presumptive cases reached who disclosed Negative')),
                ('gotten_result', models.CharField(max_length=50, verbose_name='Presumptive cases reached who has not gotten result')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_followupstatistics_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_followupstatistics_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow Up Statistics',
                'verbose_name_plural': 'Follow Up Statistics',
            },
        ),
    ]
