# Generated by Django 3.2.13 on 2022-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupstatistics',
            name='called_back',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases called back'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='disclosed_negative',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases reached who disclosed Negative'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='disclosed_not_tested',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases reached who disclosed not tested'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='disclosed_positive',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases reached who disclosed Positive'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='disclosed_result',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases reached who did not disclose result'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='disclosed_tested',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases reached who disclosed tested'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='gotten_result',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases reached who has not gotten result'),
        ),
        migrations.AlterField(
            model_name='followupstatistics',
            name='responded',
            field=models.CharField(default=0, max_length=25, verbose_name='Presumptive cases responded (reached?)'),
        ),
    ]
