# Generated by Django 3.2.13 on 2022-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='facebook_twitter_instagram',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='friends_family',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='handbill_posters',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='ppmvs',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='radio',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='religious_settings',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='schools',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='sms',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='training_and_campaign',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='sourcehotlineinformation',
            name='tv',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
