# Generated by Django 3.2.13 on 2022-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendergeographical',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='geographicaldistribution',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
