# Generated by Django 3.2.13 on 2022-07-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20220707_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenderDistributionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('abia', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='abia', to='home.call', verbose_name='Abia')),
                ('adamawa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='adamawa', to='home.call', verbose_name='Adamawa')),
                ('akwa_ibom', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='akwa_ibom', to='home.call', verbose_name='Akwa Ibom')),
                ('anambra', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='anambra', to='home.call', verbose_name='Anambra')),
                ('bauchi', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bauchi', to='home.call', verbose_name='Bauchi')),
                ('bayelsa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bayelsa', to='home.call', verbose_name='Bayelsa')),
                ('benue', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='benue', to='home.call', verbose_name='Benue')),
                ('borno', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='borno', to='home.call', verbose_name='Borno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_genderdistributionstate_created_by', to=settings.AUTH_USER_MODEL)),
                ('cross_river', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cross_river', to='home.call', verbose_name='Cross River')),
                ('delta', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='delta', to='home.call', verbose_name='Delta')),
                ('ebonyi', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ebonyi', to='home.call', verbose_name='Ebonyi')),
                ('edo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='edo', to='home.call', verbose_name='Edo')),
                ('ekiti', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ekiti', to='home.call', verbose_name='Ekiti')),
                ('enugu', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enugu', to='home.call', verbose_name='Enugu')),
                ('fct', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fct', to='home.call', verbose_name='FCT')),
                ('gombe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='gombe', to='home.call', verbose_name='Gombe')),
                ('imo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='imo', to='home.call', verbose_name='Imo')),
                ('jigawa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='jigawa', to='home.call', verbose_name='Jigawa')),
                ('kaduna', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kaduna', to='home.call', verbose_name='Kaduna')),
                ('kano', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kano', to='home.call', verbose_name='Kano')),
                ('kastina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kastina', to='home.call', verbose_name='Kastina')),
                ('kebbi', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kebbi', to='home.call', verbose_name='Kebbi')),
                ('kogi', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kogi', to='home.call', verbose_name='Kogi')),
                ('kwara', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='kwara', to='home.call', verbose_name='Kwara')),
                ('lagos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lagos', to='home.call', verbose_name='Lagos')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_genderdistributionstate_updated_by', to=settings.AUTH_USER_MODEL)),
                ('nassarawa', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nassarawa', to='home.call', verbose_name='Nassarawa')),
                ('niger', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='niger', to='home.call', verbose_name='Niger')),
                ('ogun', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ogun', to='home.call', verbose_name='Ogun')),
                ('ondo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ondo', to='home.call', verbose_name='Ondo')),
                ('osun', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='osun', to='home.call', verbose_name='Osun')),
                ('oyo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oyo', to='home.call', verbose_name='Oyo')),
                ('plateau', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='plateau', to='home.call', verbose_name='Plateau')),
                ('rivers', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rivers', to='home.call', verbose_name='Rivers')),
                ('sokoto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sokoto', to='home.call', verbose_name='Sokoto')),
                ('taraba', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='taraba', to='home.call', verbose_name='Taraba')),
                ('yobe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='yobe', to='home.call', verbose_name='Yobe')),
                ('zamfara', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='zamfara', to='home.call', verbose_name='Zamfara')),
            ],
            options={
                'verbose_name': 'Gender Distribution by State',
                'verbose_name_plural': 'Gender Distribution by States',
            },
        ),
    ]
