# Generated by Django 3.2.13 on 2022-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='appreciation_acknowledgement',
            field=models.CharField(default=0, max_length=25, verbose_name='Appreciation/Acknowledgement'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='covid_19',
            field=models.CharField(default=0, max_length=25, verbose_name='Covid-19'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='dropped_calls',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='hoax_call',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='inquiry_for_information',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='inquiry_for_service',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='service_complaint',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='suggestions',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='technical_complaint',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='test_calls',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='escalated',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='open',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='pending',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='resolved',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='casestatus',
            name='resolved_closed',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
