# Generated by Django 3.2.13 on 2022-07-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20220707_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageInboundCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('eight', models.CharField(max_length=50, verbose_name='8:00-9:00')),
                ('nine', models.CharField(max_length=50, verbose_name='9:00-10:00')),
                ('ten', models.CharField(max_length=50, verbose_name='10:00-11:00')),
                ('eleven', models.CharField(max_length=50, verbose_name='11:00-12:00')),
                ('twelve', models.CharField(max_length=50, verbose_name='12:00-1:00')),
                ('thirteen', models.CharField(max_length=50, verbose_name='1:00-2:00')),
                ('fourteen', models.CharField(max_length=50, verbose_name='2:00-300')),
                ('fifteen', models.CharField(max_length=50, verbose_name='3:00-4:00')),
                ('sixteen', models.CharField(max_length=50, verbose_name='4:00-5:00')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_percentageinboundcalls_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_percentageinboundcalls_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Percentage (%) of Inbound Calls per Hour',
                'verbose_name_plural': 'Percentage (%) of Inbound Calls per Hour',
            },
        ),
        migrations.CreateModel(
            name='InboundStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_overall_calls', models.CharField(max_length=50, verbose_name='Total overall calls')),
                ('calls_dropped_without', models.CharField(max_length=50, verbose_name='Calls dropped without opting for service')),
                ('total_serviced_calls', models.CharField(max_length=50, verbose_name='Total Serviced calls')),
                ('calls_self_service', models.CharField(max_length=50, verbose_name='Calls opted for self service')),
                ('calls_opted_agent', models.CharField(max_length=50, verbose_name='Calls opted for agent')),
                ('calls_received_agent', models.CharField(max_length=50, verbose_name='Calls received by agent')),
                ('calls_opted_received', models.CharField(max_length=50, verbose_name='Calls opted for agent but not received')),
                ('agent_received_serviced', models.CharField(max_length=50, verbose_name='Calls opted for agent but not received and not yet serviced')),
                ('received_been_serviced', models.CharField(max_length=50, verbose_name='Calls opted for agent and not received but have been serviced')),
                ('dropped_not_called_back', models.CharField(max_length=50, verbose_name='Dropped after connecting to agent and has not been called back')),
                ('dropped_called_back', models.CharField(max_length=50, verbose_name='Dropped after connecting to agent and has been called back')),
                ('called_previous_month', models.CharField(max_length=50, verbose_name='Called Back and serviced (previous month)')),
                ('called_review_month', models.CharField(max_length=50, verbose_name='Called Back and serviced (month in review)')),
                ('called_back_service', models.CharField(max_length=50, verbose_name='Called back and serviced')),
                ('concluded_calls', models.CharField(max_length=50, verbose_name='Concluded calls to agent')),
                ('total_referred_testing', models.CharField(max_length=50, verbose_name='Total callers referred for testing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_inboundstatistics_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_inboundstatistics_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbound Statistic',
                'verbose_name_plural': 'Inbound Statistics',
            },
        ),
        migrations.CreateModel(
            name='CallsAbandonedIvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('abandoned_ivr_within', models.CharField(max_length=50, verbose_name='Abandoned on IVR within Working Hour')),
                ('abandoned_ivr_after', models.CharField(max_length=50, verbose_name='Abandoned on IVR After working Hour')),
                ('abandoned_ivr_public', models.CharField(max_length=50, verbose_name='Abandoned on IVR on Public Holidays ')),
                ('abandoned_ivr_weekend', models.CharField(max_length=50, verbose_name='Abandoned on IVR on Weekends')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_callsabandonedivr_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_callsabandonedivr_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calls Abandoned on IVR Queue',
                'verbose_name_plural': 'Calls Abandoned on IVR Queue',
            },
        ),
        migrations.CreateModel(
            name='ActualUniqueCallers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('called_back_service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='called_back_service', to='home.caller')),
                ('calls_opted_agent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calls_opted_agent', to='home.caller')),
                ('calls_opted_received', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calls_opted_received', to='home.caller')),
                ('calls_received_agent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calls_received_agent', to='home.caller')),
                ('calls_self_service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='calls_self_service', to='home.caller')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_actualuniquecallers_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_actualuniquecallers_updated_by', to=settings.AUTH_USER_MODEL)),
                ('total_overall_calls', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='total_overall_calls', to='home.caller')),
                ('total_serviced_calls', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='total_serviced_calls', to='home.caller')),
            ],
            options={
                'verbose_name': 'Actual Calls Versus Unique Callers',
                'verbose_name_plural': 'Actual Calls Versus Unique Callers',
            },
        ),
    ]
