# Generated by Django 3.2.13 on 2022-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callsabandonedivr',
            name='abandoned_ivr_after',
            field=models.CharField(default=0, max_length=25, verbose_name='Abandoned on IVR After working Hour'),
        ),
        migrations.AlterField(
            model_name='callsabandonedivr',
            name='abandoned_ivr_public',
            field=models.CharField(default=0, max_length=25, verbose_name='Abandoned on IVR on Public Holidays '),
        ),
        migrations.AlterField(
            model_name='callsabandonedivr',
            name='abandoned_ivr_weekend',
            field=models.CharField(default=0, max_length=25, verbose_name='Abandoned on IVR on Weekends'),
        ),
        migrations.AlterField(
            model_name='callsabandonedivr',
            name='abandoned_ivr_within',
            field=models.CharField(default=0, max_length=25, verbose_name='Abandoned on IVR within Working Hour'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='agent_received_serviced',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls opted for agent but not received and not yet serviced'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='called_back_service',
            field=models.CharField(default=0, max_length=25, verbose_name='Called back and serviced'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='called_previous_month',
            field=models.CharField(default=0, max_length=25, verbose_name='Called Back and serviced (previous month)'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='called_review_month',
            field=models.CharField(default=0, max_length=25, verbose_name='Called Back and serviced (month in review)'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='calls_dropped_without',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls dropped without opting for service'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='calls_opted_agent',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls opted for agent'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='calls_opted_received',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls opted for agent but not received'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='calls_received_agent',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls received by agent'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='calls_self_service',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls opted for self service'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='concluded_calls',
            field=models.CharField(default=0, max_length=25, verbose_name='Concluded calls to agent'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='dropped_called_back',
            field=models.CharField(default=0, max_length=25, verbose_name='Dropped after connecting to agent and has been called back'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='dropped_not_called_back',
            field=models.CharField(default=0, max_length=25, verbose_name='Dropped after connecting to agent and has not been called back'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='received_been_serviced',
            field=models.CharField(default=0, max_length=25, verbose_name='Calls opted for agent and not received but have been serviced'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='total_overall_calls',
            field=models.CharField(default=0, max_length=25, verbose_name='Total overall calls'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='total_referred_testing',
            field=models.CharField(default=0, max_length=25, verbose_name='Total callers referred for testing'),
        ),
        migrations.AlterField(
            model_name='inboundstatistics',
            name='total_serviced_calls',
            field=models.CharField(default=0, max_length=25, verbose_name='Total Serviced calls'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='eight',
            field=models.CharField(default=0, max_length=25, verbose_name='8:00-9:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='eleven',
            field=models.CharField(default=0, max_length=25, verbose_name='11:00-12:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='fifteen',
            field=models.CharField(default=0, max_length=25, verbose_name='3:00-4:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='fourteen',
            field=models.CharField(default=0, max_length=25, verbose_name='2:00-300'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='nine',
            field=models.CharField(default=0, max_length=25, verbose_name='9:00-10:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='sixteen',
            field=models.CharField(default=0, max_length=25, verbose_name='4:00-5:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='ten',
            field=models.CharField(default=0, max_length=25, verbose_name='10:00-11:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='thirteen',
            field=models.CharField(default=0, max_length=25, verbose_name='1:00-2:00'),
        ),
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='twelve',
            field=models.CharField(default=0, max_length=25, verbose_name='12:00-1:00'),
        ),
    ]
