# Generated by Django 3.2.13 on 2022-08-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0003_auto_20220713_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentageinboundcalls',
            name='fourteen',
            field=models.CharField(default=0, max_length=25, verbose_name='2:00-3.00'),
        ),
    ]
