# Generated by Django 3.2.13 on 2022-06-02 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_overall_calls', models.CharField(max_length=50, verbose_name='Total overall calls')),
                ('calls_dropped_without', models.CharField(max_length=50, verbose_name='Calls dropped without opting for service')),
                ('total_serviced_calls', models.CharField(max_length=50, verbose_name='Total Serviced calls')),
                ('calls_self_service', models.CharField(max_length=50, verbose_name='Calls opted for self service')),
                ('calls_opted_agent', models.CharField(max_length=50, verbose_name='Calls opted for agent')),
                ('calls_received_agent', models.CharField(max_length=50, verbose_name='Calls received by agent')),
                ('calls_opted_received', models.CharField(max_length=50, verbose_name='Calls opted for agent but not received')),
                ('agent_received_serviced', models.CharField(max_length=50, verbose_name='Calls opted for agent but not received and not yet serviced')),
                ('received_been_serviced', models.CharField(max_length=50, verbose_name='Calls opted for agent and not received but have been serviced')),
                ('dropped_not_called_back', models.CharField(max_length=50, verbose_name='Dropped after connecting to agent and has not been called back')),
                ('dropped_called_back', models.CharField(max_length=50, verbose_name='Dropped after connecting to agent and has been called back')),
                ('called_previous_month', models.CharField(max_length=50, verbose_name='Called Back and serviced (previous month)')),
                ('called_review_month', models.CharField(max_length=50, verbose_name='Called Back and serviced (month in review)')),
                ('called_back_service', models.CharField(max_length=50, verbose_name='Called back and serviced')),
                ('concluded_calls', models.CharField(max_length=50, verbose_name='Concluded calls to agent')),
                ('total_referred_testing', models.CharField(max_length=50, verbose_name='Total callers referred for testing')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_inboundstatistics_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_inboundstatistics_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
