# Generated by Django 3.2.13 on 2022-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_inboundstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategory',
            name='appreciation_acknowledgement',
            field=models.CharField(max_length=50, verbose_name='Appreciation/Acknowledgement'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='covid_19',
            field=models.CharField(max_length=50, verbose_name='Covid-19'),
        ),
        migrations.AlterField(
            model_name='casecategory',
            name='non_tb_calls',
            field=models.CharField(max_length=50, verbose_name='Non-TB Calls'),
        ),
    ]
