# Generated by Django 3.2.13 on 2022-06-02 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20220602_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecategory',
            options={'verbose_name': 'Case Category', 'verbose_name_plural': 'Case Category'},
        ),
        migrations.AlterModelOptions(
            name='casestatus',
            options={'verbose_name': 'Case Status', 'verbose_name_plural': 'Case Status'},
        ),
        migrations.AlterModelOptions(
            name='genderdistribution',
            options={'verbose_name': 'Gender Distribution', 'verbose_name_plural': 'Gender Distributions'},
        ),
        migrations.AlterModelOptions(
            name='geographicaldistribution',
            options={'verbose_name': 'Geographical Distribution', 'verbose_name_plural': 'Geographical Distribution'},
        ),
        migrations.AlterModelOptions(
            name='inboundstatistics',
            options={'verbose_name': 'Inbound Statistic', 'verbose_name_plural': 'Inbound Statistics'},
        ),
        migrations.AlterModelOptions(
            name='languageselection',
            options={'verbose_name': 'Language Selection', 'verbose_name_plural': 'Language Selection'},
        ),
        migrations.AlterModelOptions(
            name='sourcehotlineinformation',
            options={'verbose_name': 'Source Hotline Information', 'verbose_name_plural': 'Source Hotline Information'},
        ),
        migrations.CreateModel(
            name='PresumptiveTestedPositive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('male', models.CharField(max_length=30)),
                ('female', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_presumptivetestedpositive_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_presumptivetestedpositive_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presumptive Tested Positive',
                'verbose_name_plural': 'Presumptive Tested Positive',
            },
        ),
        migrations.CreateModel(
            name='PresumptiveCasesTested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('male', models.CharField(max_length=30)),
                ('female', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_presumptivecasestested_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_presumptivecasestested_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presumptive Cases Tested',
                'verbose_name_plural': 'Presumptive Cases Tested',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('male', models.CharField(max_length=30)),
                ('female', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_call_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_call_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Call',
                'verbose_name_plural': 'Calls',
            },
        ),
        migrations.AddField(
            model_name='genderdistribution',
            name='calls',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.call'),
        ),
        migrations.AddField(
            model_name='genderdistribution',
            name='presumptive_cases_tested',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.presumptivecasestested'),
        ),
        migrations.AddField(
            model_name='genderdistribution',
            name='presumptive_tested_positive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.presumptivetestedpositive'),
        ),
    ]
