# Generated by Django 3.2.13 on 2022-07-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220707_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedcallbreakdown',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='reasonnottested',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='referralstatus',
            name='current',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
