# Generated by Django 3.2.13 on 2022-07-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20220707_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresumptiveGenderDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presumptive_presumptivegenderdistribution_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presumptive_presumptivegenderdistribution_updated_by', to=settings.AUTH_USER_MODEL)),
                ('presumptive_cases_tested', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.presumptivecasestested', verbose_name='Presumptive cases tested based on Gender')),
                ('presumptive_tested_positive', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.presumptivetestedpositive', verbose_name='Presumptive who tested positive based on Gender')),
            ],
            options={
                'verbose_name': 'Presumptive Gender Distribution',
                'verbose_name_plural': 'Presumptive Gender Distributions',
            },
        ),
        migrations.CreateModel(
            name='PresumptiveCasesTestedState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('abia', models.CharField(max_length=30)),
                ('adamawa', models.CharField(max_length=30)),
                ('akwa_ibom', models.CharField(max_length=30)),
                ('anambra', models.CharField(max_length=30)),
                ('bauchi', models.CharField(max_length=30)),
                ('bayelsa', models.CharField(max_length=30)),
                ('benue', models.CharField(max_length=30)),
                ('borno', models.CharField(max_length=30)),
                ('cross_river', models.CharField(max_length=30)),
                ('delta', models.CharField(max_length=30)),
                ('ebonyi', models.CharField(max_length=30)),
                ('edo', models.CharField(max_length=30)),
                ('ekiti', models.CharField(max_length=30)),
                ('enugu', models.CharField(max_length=30)),
                ('fct', models.CharField(max_length=30)),
                ('gombe', models.CharField(max_length=30)),
                ('imo', models.CharField(max_length=30)),
                ('jigawa', models.CharField(max_length=30)),
                ('kaduna', models.CharField(max_length=30)),
                ('kano', models.CharField(max_length=30)),
                ('kastina', models.CharField(max_length=30)),
                ('kebbi', models.CharField(max_length=30)),
                ('kogi', models.CharField(max_length=30)),
                ('kwara', models.CharField(max_length=30)),
                ('lagos', models.CharField(max_length=30)),
                ('nassarawa', models.CharField(max_length=30)),
                ('niger', models.CharField(max_length=30)),
                ('ogun', models.CharField(max_length=30)),
                ('ondo', models.CharField(max_length=30)),
                ('osun', models.CharField(max_length=30)),
                ('oyo', models.CharField(max_length=30)),
                ('plateau', models.CharField(max_length=30)),
                ('rivers', models.CharField(max_length=30)),
                ('sokoto', models.CharField(max_length=30)),
                ('taraba', models.CharField(max_length=30)),
                ('yobe', models.CharField(max_length=30)),
                ('zamfara', models.CharField(max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presumptive_presumptivecasestestedstate_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presumptive_presumptivecasestestedstate_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presumptive cases tested by state',
                'verbose_name_plural': 'Presumptive cases tested by state',
            },
        ),
    ]
