# Generated by Django 3.2.13 on 2022-07-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220707_1225'),
        ('presumptive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='abia',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='adamawa',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='akwa_ibom',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='anambra',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='bauchi',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='bayelsa',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='benue',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='borno',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='cross_river',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='delta',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='ebonyi',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='edo',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='ekiti',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='enugu',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='fct',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='gombe',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='imo',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='jigawa',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='kaduna',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='kano',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='kastina',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='kebbi',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='kogi',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='kwara',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='lagos',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='nassarawa',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='niger',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='ogun',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='ondo',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='osun',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='oyo',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='plateau',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='rivers',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='sokoto',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='taraba',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='yobe',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivecasestestedstate',
            name='zamfara',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AlterField(
            model_name='presumptivegenderdistribution',
            name='presumptive_cases_tested',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='presumptive_cases_tested', to='home.call', verbose_name='Presumptive cases tested based on Gender'),
        ),
        migrations.AlterField(
            model_name='presumptivegenderdistribution',
            name='presumptive_tested_positive',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='presumptive_tested_positive', to='home.call', verbose_name='Presumptive who tested positive based on Gender'),
        ),
    ]
